//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:45,
			formatAnswer:"",
			pict:"./Images/01.jpg"},
	task2 = {task:``,
 			sec:45,
 			formatAnswer:"",
 			pict:"./Images/02.jpg"},
	task3 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/03.jpg"},
	task4 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/04.jpg"},
	task5 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/05.jpg"},
	task6 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/06.jpg"},
	task7 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/07.jpg"},
	task8 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/08.jpg"},
	task9 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/09.jpg"},
	task10 = {task:``,
			sec:45,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/10.jpg"}
	
			];


const answers = [
 	task1 = {task:``,
			sec:10,
			sizeFormatAnswer: `16rem`,
			formatAnswer:"Леонтьев",
			pict:"./Images/01.jpg"},
	task2 = {task:``,
 			sec:10,
 			formatAnswer:"Виа Гра",
 			pict:"./Images/02.jpg"},
	task3 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			formatAnswer:"Лепс",
			pict:"./Images/03.jpg"},
	task4 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			formatAnswer:"Rolling stones",
			pict:"./Images/04.jpg"},
	task5 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Чистяков(группа Ноль)",
			pict:"./Images/05.jpg"},
	task6 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Александр Барыкин",
			pict:"./Images/06.jpg"},
	task7 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Ленинград",
			pict:"./Images/07.jpg"},
	task8 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Борис Моисеев",
			pict:"./Images/08.jpg"},
	task9 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Ария",
			pict:"./Images/09.jpg"},
	task10 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Red Hot Chilly Pappers",
			pict:"./Images/10.jpg"}
	
			];

