//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:25,
			formatAnswer:"",
			pict:"./Images/01_prizrak.jpg"},
	task2 = {task:``,
 			sec:25,
 			formatAnswer:"",
 			pict:"./Images/02_devyat_s_pol.jpg"},
	task3 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/03_adrenal.jpg"},
	task4 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/04_krasotka.jpg"},
	task5 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/05_pyatd_ott.jpg"},
	task6 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/06_titan.jpg"},
	task7 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/07_kaligula.jpg"},
	task8 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/08_sumerki.jpg"},
	task9 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/09_got.jpg"},
	task10 = {task:``,
			sec:25,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/10_nov_pr_shurika.jpg"}
	
			];


const answers = [
 	task1 = {task:``,
			sec:10,
			sizeFormatAnswer: `16rem`,
			formatAnswer:"Призрак",
			pict:"./Images/01_prizrak.jpg"},
	task2 = {task:``,
 			sec:10,
 			formatAnswer:"9 с половиной недель",
 			pict:"./Images/02_devyat_s_pol.jpg"},
	task3 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			formatAnswer:"Адреналин",
			pict:"./Images/03_adrenal.jpg"},
	task4 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			formatAnswer:"Красотка",
			pict:"./Images/04_krasotka.jpg"},
	task5 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Пятьдесят оттенков серого",
			pict:"./Images/05_pyatd_ott.jpg"},
	task6 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Титаник",
			pict:"./Images/06_titan.jpg"},
	task7 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Калигула",
			pict:"./Images/07_kaligula.jpg"},
	task8 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Сумерки",
			pict:"./Images/08_sumerki.jpg"},
	task9 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Игра престолов",
			pict:"./Images/09_got.jpg"},
	task10 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:"Новые приключения Шурика",
			pict:"./Images/10_nov_pr_shurika.jpg"}
	
			];

