//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,			
			pict:"./Images/1_od_doma.jpg"},
 	task2 = {task:``,
 			sec:30,
 			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
 			pict:"./Images/2_kr_ore.jpg"},
	task3 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/3_karn_n.jpg"},
	task4 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/4_greml.jpg"},
	task5 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/5_vech_h_dik.jpg"},
	task6 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/6_moro.jpg"},
	task7 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/7_be_saha.jpg"},
	task8 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/8_o_chm_g_m.jpg"},
	task9 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/9_kudr_sui.jpg"},
	task10 = {task:``,
			sec:30,
			formatAnswer:"",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/99_ir_s.jpg"},
			];

console.log (tasks[0].pict);

const answers = [
 	task1 = {task:``,
			sec:10,
			sizeFormatAnswer: "8rem",
			formatAnswer:"Один дома",
			pict:tasks[0].pict},
	task2 = {task:``,
 			sec:10,
 			formatAnswer:"Крепкий орешек",
 			pict:tasks[1].pict},
	task3 = {task: ``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`10rem`,
			formatAnswer:"Карновальная ночь",
			pict:tasks[2].pict},
	task4 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`10rem`,
			formatAnswer:"Гремлины",
			pict:tasks[3].pict},
	task5 = {task:``,
			sec:10,
			sizeFormatAnswer: "7rem",
			sizeTask:`9rem`,
			formatAnswer:"Вечера на хуторе близь Диканьки",
			pict:tasks[4].pict},
	task6 = {task:``,
			sec:10,
			sizeFormatAnswer: `8rem`,
			sizeTask:``,
			formatAnswer:"Морозко",
			pict:tasks[5].pict},
	task7 = {task:``,
			sec:10,
			sizeFormatAnswer: `8rem`,
			sizeTask:`12rem`,
			formatAnswer:"Бедная Саша",
			pict:tasks[6].pict},
	task8 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`9rem`,
			formatAnswer:"О чем говорят мужчины",
			pict:tasks[7].pict},
	task9 = {task:``,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`12rem`,
			formatAnswer:"Кудряшка Сью",
			pict:tasks[8].pict},
	task10 = {task:``,
			sec:10,
			sizeFormatAnswer: `7rem`,
			sizeTask:`14rem`,
			formatAnswer:"Ирония судьбы или с легким паром",
			pict:tasks[9].pict}
	
			];

