//задания на уровень
const tasks = [
 	task1 = {task:`П П, М В!`,
 			sec:60,
 			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
 			pict:"./Images/1_dg_ud.jpg"},
	task2 = {task:`А - Э Н П.`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,			
			pict:"./Images/2_alk_n_p.jpg"},
	task3 = {task:`К же Е П? О же П!`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/3_k_p_p.jpg"},
	task4 = {task:`Р Т - О М!`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/4_rustom.jpg"},
	task5 = {task:`Ш по У П А и Д.`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/5_sh_po_utr.jpg"},
	task6 = {task:`у В Н С на С Б? Б.`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/6_nes_sl_str.png"},
	task7 = {task:`я Т П Б!`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/7_ya_tr_pord_bank.png"},
	task8 = {task:`и Ш я в Т Т В, а?`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/8_ch_moe_s_m_na_gr_shuh.jpg"},
	task9 = {task:`Г, О Л.`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/9_gulc_o_l.jpg"},
	task10 = {task:`Б, Д М!`,
			sec:60,
			formatAnswer:"Формат ответа: фраза на русском языке",
			sizeFormatAnswer: `3rem`,
			pict:"./Images/10_beg_d_m.jpg"},
			];


const answers = [
 	task1 = {task:`Пасть порву, моргала выколю`,
 			sec:10,
 			formatAnswer:"",
 			pict:"./Images/1_dg_ud.jpg"},
	task2 = {task:`Алкоголики - это наш профиль`,
			sec:10,
			formatAnswer:"",
			pict:"./Images/2_alk_n_p.jpg"},
	task3 = {task:`Кто ж его посадит, он же памятник`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`10rem`,
			formatAnswer:"",
			pict:"./Images/2_alk_n_p.jpg"},
	task4 = {task:`Руссо туристо - облико морале!`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`11rem`,
			formatAnswer:"",
			pict:"./Images/4_rustom.jpg"},
	task5 = {task:`Шампанское по утрам пьют аристократы и дегенераты`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`9rem`,
			formatAnswer:"",
			pict:"./Images/5_sh_po_utr.jpg"},
	task6 = {task:`Несчастные случаи на стройке были? Будут.`,
			sec:10,
			sizeFormatAnswer: `12rem`,
			sizeTask:``,
			formatAnswer:"",
			pict:"./Images/6_nes_sl_str.png"},
	task7 = {task:`Я требую продолжения банкета!`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`12rem`,
			formatAnswer:"",
			pict:"./Images/7_ya_tr_pord_bank.png"},
	task8 = {task:`И шо я в тебя такой влюбленный, а?`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`11rem`,
			formatAnswer:"",
			pict:"./Images/8_ch_moe_s_m_na_gr_shuh.jpg"},
	task9 = {task:`Гюльчитай, открой личико.`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`14rem`,
			formatAnswer:"",
			pict:"./Images/9_gulc_o_l.jpg"},
	task10 = {task:`Беги, дядь Мить!`,
			sec:10,
			sizeFormatAnswer: ``,
			sizeTask:`14rem`,
			formatAnswer:"",
			pict:"./Images/10_beg_d_m.jpg"}
	
			];

